### ISSUE TITLE
DockerHub Image?

### ISSUE THREAD

**Issue by AndrewQuijano** [eurecom-s3/symcc#163]
Hello,
Is there a plan to publish the docker image on DockerHub for easier pulling instead of just installing it? I am open to provide the update to GitHub actions to allow building and pushing the image to DockerHub if you can create a secret with the DockerHub password and what will be the docker hub account name.

**Comment by AndrewQuijano** [comment]
This would be a quick edit to the GitHub Actions

https://github.com/docker/build-push-action

**Comment by aurelf** [comment]
Hi, 
sure that's something we had in mind, in particular to simplify SymQEMU tests. Now we are splitting the runtime to a separate repo (PR #162 ), so it's not really a motivation anymore. 
That said, making available a Docker image up to date with the main branch is a good idea anyway.  
I thought maybe doing a github Package, instead of DockerHub? Maybe this would be better (easier to use here maybe?) although the two options are not exclusive.

**Comment by AndrewQuijano** [comment]
I figure more options the better, at least with DockerHub, the workflow is pretty well documented and I don't mind giving a shot at getting the export going for you, (once the secret is populated).

**Comment by aurelf** [comment]
No need to wait for the other PRs, it would be great if you could make a PR, I created the secrets : 
```
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

```
this should allow to push images to eurecoms3/symcc on DockerHub.

**Comment by AndrewQuijano** [comment]
https://github.com/eurecom-s3/symcc/pulls
