### ISSUE TITLE
C++ I/O intercept function support

### ISSUE THREAD

**Issue by wuruoyu** [eurecom-s3/symcc#8]
Hi, 

I am wondering do you have any plan to support the interception of C++ file I/O function (e.g. std::getline). Thank you in advance!

Ruoyu

**Comment by sebastianpoeplau** [comment]
Hi @wuruoyu,

In principle, C++ I/O is already supported: we hook the libc functions that libc++ uses to implement C++ I/O. So if you have an [instrumented C++ runtime](https://github.com/eurecom-s3/symcc/blob/master/docs/C%2B%2B.txt), things should already work as expected. For example, `std::fstream` and friends are [implemented](https://github.com/llvm/llvm-project/blob/7bf168390fd05460b1c0df3fa570758c6be718fd/libcxx/include/fstream#L555) with `fopen`. Similarly, we support `std::cin` for reading from standard input.

Have you found a use case where symbolic C++ I/O doesn't work as it should? If so, would you mind sharing the program so that we can investigate?

Cheers,
Sebastian

**Comment by wuruoyu** [comment]
Oh it's my bad. It seems that I set up the SYMCC_INPUT_FILE incorrectly. Now it works as expected, thank you!

**Comment by sebastianpoeplau** [comment]
The mechanism is a bit fragile at the moment because we expect the contents of `SYMCC_INPUT_FILE` as a substring in the file name that the program passes to `open` or `fopen` (possibly via the C++ standard library). I guess it would be better to transform both names to some canonical form and then check for an exact match...

**Comment by sebastianpoeplau** [comment]
Anyway, glad it works for you now!
